FROM node:16.9.0-alpine as builder
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
ARG ENVIRONMENT
ENV REACT_APP_ENV ${ENVIRONMENT}
RUN npm run build

FROM nginx:1.20.1-alpine
COPY --from=builder /app/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build /usr/share/nginx/html