apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: maple-fighters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: maplefighters/frontend:2.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: maple-fighters
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: frontend
